### ISSUE TITLE
Simple Live Feed not working

### ISSUE THREAD

**Issue by debdipta** [upstox/upstox-python#26]
I have a very simple live feed program to get live feed data, but there is no response:
MY code is as below:
```
`from upstox_api.api import *

import datetime
import sys

def event_handler_quote_update(message):
    print("Quote Update: %s" % str(message))
    sys.stdout.flush()

u = Upstox('xxxxxx', 'xxxxxx')

inst = u.get_master_contract('NSE_EQ')
inst = u.get_master_contract('NSE_INDEX')

u.subscribe(u.get_instrument_by_symbol('NSE_EQ', 'TATAMTRDVR'), LiveFeedType.Full)

u.set_on_quote_update(event_handler_quote_update)

u.start_websocket(False)`
```

**Comment by debdipta** [comment]
Error as below:
```
C:\Firmware>C:\Users\ghosdebd\AppData\Local\Programs\Python\Python37\python.exe test.py
Traceback (most recent call last):
  File "C:\Users\ghosdebd\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "C:\Users\ghosdebd\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\util\connection.py", line 80, in create_connection
    raise err
  File "C:\Users\ghosdebd\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\util\connection.py", line 70, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ghosdebd\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "C:\Users\ghosdebd\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 344, in _make_request
    self._validate_conn(conn)
  File "C:\Users\ghosdebd\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 843, in _validate_conn
    conn.connect()
  File "C:\Users\ghosdebd\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connection.py", line 316, in connect
    conn = self._new_conn()
  File "C:\Users\ghosdebd\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x000002143E554B48>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ghosdebd\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Users\ghosdebd\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Users\ghosdebd\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\util\retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.upstox.com', port=443): Max retries exceeded with url: /index/profile (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000002143E554B48>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 10, in <module>
    u = Upstox('u0L3rZYR6daWVeWHgGxEE6VIMfEWJVJC8SmJCpjP', 'f9644335cc5c72ac5f1c7ad6bce557822201a1c7')
  File "C:\Users\ghosdebd\AppData\Local\Programs\Python\Python37\lib\site-packages\upstox_api\api.py", line 290, in __init__
    profile = self.api_call_helper('profile', PyCurlVerbs.GET, None, None)
  File "C:\Users\ghosdebd\AppData\Local\Programs\Python\Python37\lib\site-packages\upstox_api\api.py", line 853, in api_call_helper
    response = self.api_call(url, http_method, data)
  File "C:\Users\ghosdebd\AppData\Local\Programs\Python\Python37\lib\site-packages\upstox_api\api.py", line 884, in api_call
    r = requests.get(url, headers=headers)
  File "C:\Users\ghosdebd\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\ghosdebd\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\ghosdebd\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\ghosdebd\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\ghosdebd\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.upstox.com', port=443): Max retries exceeded with url: /index/profile (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000002143E554B48>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))

C:\Firmware>
```

**Comment by debdipta** [comment]
Issue fixed after installing proper versions of dependent packages and downflgrading websocket to 0.40.
